import { Head, Link } from '@inertiajs/react'
import { useUserImportProgress } from '../../../hooks/useUserImportProgress'
import { importStatusLabel } from './status'

type Import = { id: string; filename: string; status: string; totalCount: number; processedCount: number; createdCount: number; rejectedCount: number; progressPercent: number; failureMessage?: string }
type Result = { rowNumber: number; status: string; normalizedEmail?: string; normalizedRole?: string; errorMessage?: string }

export default function UserImportShow({ userImport, results, pagination }: { userImport: Import; results: Result[]; pagination: { page: number; totalPages: number; totalItems: number } }) {
  const { updating } = useUserImportProgress(userImport.id)
  return <section className="page-section"><Head title="Detalhe da importação · Umanni" /><Link href="/admin/user_imports" className="text-button">Voltar ao histórico</Link><div className="page-heading"><div><div className="eyebrow">Importação</div><h1>{userImport.filename}</h1><p>{userImport.processedCount} de {userImport.totalCount} linhas processadas.</p></div><span className={`sync-state ${updating ? 'is-updating' : ''}`}>{updating ? 'Atualizando…' : `${userImport.progressPercent}%`}</span></div>{userImport.failureMessage && <p className="form-summary">{userImport.failureMessage}</p>}<div className="metric-grid"><article className="metric-card"><span>Criadas</span><strong>{userImport.createdCount}</strong></article><article className="metric-card metric-coral"><span>Rejeitadas</span><strong>{userImport.rejectedCount}</strong></article><article className="metric-card metric-navy"><span>Estado</span><strong>{importStatusLabel(userImport.status)}</strong></article></div><h2>Relatório seguro</h2><p className="sr-only" role="status" aria-live="polite">{updating ? 'Atualizando importação' : 'Importação atualizada'}</p><div className="user-table" role="table" aria-label="Resultados por linha"><div className="table-head" role="row"><span>Linha</span><span>E-mail</span><span>Resultado</span></div>{results.map(result => <article className="user-row" role="row" key={result.rowNumber}><span role="cell">{result.rowNumber}</span><span role="cell">{result.normalizedEmail || '—'}</span><span role="cell">{result.errorMessage || importStatusLabel(result.status)}</span></article>)}</div><p>{pagination.totalItems} resultados · página {pagination.page} de {pagination.totalPages}</p></section>
}
